import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About - KR-CODE",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="mx-auto max-w-5xl py-10 px-5">
      <h1 className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl text-center mb-10">
        About This App
      </h1>

      <p className="mb-3 text-xl">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ad
        quibusdam sunt molestiae dolorem deserunt asperiores numquam consectetur
        cumque. Sequi corrupti vel quaerat earum ipsa ex illo ratione
        exercitationem ducimus.
      </p>
      <p className="mb-3 text-xl">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ad
        quibusdam sunt molestiae dolorem deserunt asperiores numquam consectetur
        cumque. Sequi corrupti vel quaerat earum ipsa ex illo ratione
        exercitationem ducimus.
      </p>
      <p className="mb-3 text-xl">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ad
        quibusdam sunt molestiae dolorem deserunt asperiores numquam consectetur
        cumque. Sequi corrupti vel quaerat earum ipsa ex illo ratione
        exercitationem ducimus.
      </p>
      <p className="mb-3 text-xl">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ad
        quibusdam sunt molestiae dolorem deserunt asperiores numquam consectetur
        cumque. Sequi corrupti vel quaerat earum ipsa ex illo ratione
        exercitationem ducimus.
      </p>
      <p className="mb-3 text-xl">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ad
        quibusdam sunt molestiae dolorem deserunt asperiores numquam consectetur
        cumque. Sequi corrupti vel quaerat earum ipsa ex illo ratione
        exercitationem ducimus.
      </p>
      <p className="mb-3 text-xl">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ad
        quibusdam sunt molestiae dolorem deserunt asperiores numquam consectetur
        cumque. Sequi corrupti vel quaerat earum ipsa ex illo ratione
        exercitationem ducimus.
      </p>
    </div>
  );
};

export default AboutPage;
