import Hero from "@/components/home/Hero";
import Plans from "@/components/home/Plans";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home - KR-CODE",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div>
      <section className="bg-gray-900 text-white">
        <Hero />

        <h2 className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl m-auto mb-10 text-center">
          Choose Your Website Plan
        </h2>

        <div className="m-auto flex items-center justify-center my-7 flex-wrap md:gap-7">
          <Plans />
          <Plans />
          <Plans />
        </div>
      </section>
    </div>
  );
};

export default HomePage;
