import { cookies } from "next/headers";
import AddArticleForm from "./AddArticleForm";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { verifyTokenForPage } from "@/utils/verifyToken";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const AdminPage = () => {
  const token = cookies().get("jwtToken")?.value || "";
  if (!token) return redirect("/");

  const user = verifyTokenForPage(token);
  if (user?.isAdmin === false) return redirect("/");

  return (
    <div>
      <AddArticleForm />
    </div>
  );
};

export default AdminPage;
