import { getSingleArticle } from "@/apiCalls/articleApiCall";
import AddCommentForm from "@/components/comments/AddCommentForm";
import CommentItem from "@/components/comments/CommentItem";
import { SingleArticle } from "@/utils/types";
import { Metadata } from "next";
import { BsPostcard } from "react-icons/bs";
import { cookies } from "next/headers";
import { verifyTokenForPage } from "@/utils/verifyToken";

export const metadata: Metadata = {
  title: "Single Article",
  description: "Generated by create next app",
};

interface Props {
  params: { id: string };
}

const page = async ({ params }: Props) => {
  const { id } = params;

  const token = cookies().get("jwtToken")?.value || "";
  const user = verifyTokenForPage(token);

  const article: SingleArticle = await getSingleArticle(id);

  return (
    <section className="m-auto w-full px-5 pt-8 md:w-3/4">
      <article className="rounded-lg border border-gray-100 bg-white p-4 shadow-sm transition hover:shadow-lg sm:p-6 dark:border-gray-800 dark:bg-gray-900 dark:shadow-gray-700/25">
        <span className="inline-block rounded bg-blue-600 p-2 text-white dark:bg-blue-700">
          <BsPostcard size={20} />
        </span>

        <h3 className="mt-0.5 text-lg font-medium text-gray-900 dark:text-white">
          {article.title}
        </h3>

        <time
          dateTime="2022-10-10"
          className="block text-xs text-gray-500 dark:text-gray-400"
        >
          {new Date(article.createdAt).toDateString()}
        </time>

        <p className="mt-2  text-sm/relaxed text-gray-500 dark:text-gray-400">
          {article.description}
        </p>
      </article>

      {user ? (
        <AddCommentForm articleId={article.id} />
      ) : (
        <div>
          <p className="mt-10 text-center text-sm/relaxed text-amber-600">
            to write a comment you should login first
          </p>
        </div>
      )}

      <h1 className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-3xl w-fit m-auto my-10">
        Comments
      </h1>

      {article.comments?.map((comment) => (
        <CommentItem key={comment.id} comment={comment} user={user} />
      ))}
    </section>
  );
};

export default page;
